tap 'caskroom/fonts'
tap 'jamieconnolly/formulae'

brew 'ack'
brew 'findutils'
brew 'git'
brew 'gnu-tar'
brew 'gnupg21'
brew 'htop-osx'
brew 'hub'
brew 'node-build'
brew 'nodenv'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'pyenv-virtualenv-ext'
brew 'rbenv'
brew 'rbenv-binstubs'
brew 'rbenv-default-gems'
brew 'ruby-build'
brew 'spark'

cask '1password'
cask 'atom'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'flux'
cask 'franz'
cask 'github-desktop'
cask 'google-chrome'
cask 'postico'
cask 'recordit'
cask 'the-unarchiver'

cask 'font-input'
