tap 'caskroom/fonts'
tap 'jamieconnolly/formulae'

brew 'ack'
brew 'autoconf'
brew 'forego'
brew 'git'
brew 'glide'
brew 'gnupg@2.1'
brew 'guetzli'
brew 'handles'
brew 'hub'
brew 'launch_socket_server', restart_service: true
brew 'launchdns', restart_service: true
brew 'mas'
brew 'nginx', restart_service: true
brew 'node'
brew 'nodenv'
brew 'openssl'
brew 'pkg-config'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'pyenv-virtualenv-ext'
brew 'python'
brew 'rbenv'
brew 'rbenv-binstubs'
brew 'rbenv-default-gems'
brew 'readline'
brew 'ruby'
brew 'shellcheck'
brew 'yarn'
brew 'zsh'

cask '1password'
cask 'atom'
cask 'bartender'
cask 'polymail'
cask 'quitter'
cask 'recordit'
cask 'the-unarchiver'

cask 'font-input'
