#!/usr/bin/env zsh
# Summary: Quickly jump into a project directory

if ! builtin cd "$@" &>/dev/null; then
  if [ -s "${PROJECT_HOME}/${GITHUB_USER}/${1}" ]; then
    builtin cd "${PROJECT_HOME}/${GITHUB_USER}/${1}" && return
  elif [ -s "${PROJECT_HOME}/${1}" ]; then
    builtin cd "${PROJECT_HOME}/${1}" && return
  elif [ ! -d "$1" ]; then
    echo "cd: no such directory: ${1}" >&2 && return 1
  else
    echo "cd: no such file or directory: ${1}" >&2 && return 1
  fi
fi
