#!/bin/bash
# Usage: script/extract-secrets
# Summary: Extract all secrets from 1Password

set -e
cd "$(git rev-parse --show-toplevel)"

if [ -z "$OP_SESSION_my" ]; then
  echo "==> Logging into 1Password…"
  eval $(op signin my.1password.com jamie@jamieconnolly.com)
fi

echo "==> Setting up GPG…"
if ! command -v gpg >/dev/null 2>&1; then
  echo "!!! Error: GPG is not installed" >&2
  exit 1
fi

chmod 700 ~/.gnupg

op get document 'GPG - Owner Trust' > ~/.gnupg/jamie@jamieconnolly.com.ownertrust.gpg-txt
op get document 'GPG - Public Key' > ~/.gnupg/jamie@jamieconnolly.com.public.gpg-key
op get document 'GPG - Secret Subkeys' > ~/.gnupg/jamie@jamieconnolly.com.private.gpg-key

gpg --import ~/.gnupg/jamie@jamieconnolly.com.public.gpg-key ~/.gnupg/jamie@jamieconnolly.com.private.gpg-key
gpg --import-ownertrust < ~/.gnupg/jamie@jamieconnolly.com.ownertrust.gpg-txt

rm ~/.gnupg/jamie@jamieconnolly.com.ownertrust.gpg-txt
rm ~/.gnupg/jamie@jamieconnolly.com.private.gpg-key
rm ~/.gnupg/jamie@jamieconnolly.com.public.gpg-key
