#!/bin/bash
# Usage: script/extract-secrets
# Summary: Extract all secrets from 1Password

set -e
cd "$(git rev-parse --show-toplevel)"

if [ -z "$OP_SESSION_my" ]; then
  echo "==> Logging into 1Password…"
  eval "$(op signin --account my.1password.com)"
fi

echo "==> Setting up GPG…"
if ! command -v gpg >/dev/null 2>&1; then
  echo "!!! Error: GPG is not installed" >&2
  exit 1
fi

mkdir ~/.gnupg

op document get 34s25y7775gw7dakdp6x6u6mbm > ~/.gnupg/jamie@jamieconnolly.com.public.gpg-key
chmod 600 ~/.gnupg/jamie@jamieconnolly.com.public.gpg-key

op document get 7tm2hnksdvdztek5rj7irwjc2i > ~/.gnupg/jamie@jamieconnolly.com.private.gpg-key
chmod 600 ~/.gnupg/jamie@jamieconnolly.com.private.gpg-key

chmod 700 ~/.gnupg

gpg --import ~/.gnupg/jamie@jamieconnolly.com.public.gpg-key \
             ~/.gnupg/jamie@jamieconnolly.com.private.gpg-key
