#!/bin/bash
# Usage: script/set-defaults
# Summary: Set reasonable macOS defaults

set -e
cd "$(git rev-parse --show-toplevel)"

echo "==> Setting macOS defaults…"

# Dock: Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true
defaults write com.apple.Dock autohide-delay -float 0

# Dock: Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Dock: Don't show indicators for open applications
defaults write com.apple.dock show-process-indicators -bool false

# Dock: Minimize windows into application icon
defaults write com.apple.dock minimize-to-application -bool true

# Dock: Group windows by application
defaults write com.apple.dock expose-group-apps -bool true

# Dock: Show only active applications
defaults write com.apple.dock static-only -bool true

# Dock: Move the dock to the left
defaults write com.apple.dock orientation -string "left"

# Dock: Make the dock icons a bit smaller
defaults write com.apple.dock tilesize -int 48

# Finder: Don't show icons on the desktop
defaults write com.apple.finder CreateDesktop -bool false

# Finder: Don't write .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Finder: Minimize window when double clicking title bar
defaults write NSGlobalDomain AppleMiniaturizeOnDoubleClick -bool true

# Finder: Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Finder: Open new windows on the user's home directory
defaults write com.apple.finder NewWindowTarget -string "PfHm"

# Finder: Search within current directory
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Finder: Set column view as the default
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

# Finder: Show hard disks in sidebar
defaults write com.apple.sidebarlists ShowHardDisks -bool true

# Safari: Ask websites not to track me
defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true

# Safari: Disable AutoFill
defaults write com.apple.Safari AutoFillCreditCardData -bool false
defaults write com.apple.Safari AutoFillFromAddressBook -bool false
defaults write com.apple.Safari AutoFillMiscellaneousForms -bool false
defaults write com.apple.Safari AutoFillPasswords -bool false

# Safari: Disable Java
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabledForLocalFiles -bool false

# Safari: Show Develop menu in the menu bar
defaults write com.apple.safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true
defaults write com.apple.safari IncludeDevelopMenu -bool true
defaults write com.apple.safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true

# Safari: Start with all windows from last session
defaults write com.apple.Safari AlwaysRestoreSessionAtLaunch -bool true

# Wi-Fi: Enable Private Cloudflare DNS servers (1.1.1.1)
networksetup -setdnsservers Wi-Fi 1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001
