#!/bin/bash
# Usage: script/setup
# Summary: Install all dotfiles into the home directory

set -e
cd "$(git rev-parse --show-toplevel)"

DOTFILESDIR="$(pwd -P)"

for DOTFILE in *; do
  HOMEFILE="$HOME/.$DOTFILE"
  [ -d $DOTFILE ] && DOTFILE="$DOTFILE/"
  DIRFILE="$DOTFILESDIR/$DOTFILE"

  # Don't mess with Codespaces' default GPG/SSH setup
  if [ -n "$CODESPACES" ]; then
    echo $DOTFILE | egrep -q '^(gnupg|ssh)/' && continue
  fi

  # Don't try to install documentation/script files
  echo $DOTFILE | egrep -q '(^script/$|\.md$|\.txt$)' && continue

  # Remove .zsh extensions
  echo $DOTFILE | grep -q '\.zsh' && HOMEFILE="$HOME/.$(echo $DOTFILE | sed -e 's/\.zsh//')"

  if [ -L "$HOMEFILE" ] && ! [ -d $DOTFILE ]; then
    ln -sfv "$DIRFILE" "$HOMEFILE"
  else
    rm -rv "$HOMEFILE" 2>/dev/null || true
    ln -sv "$DIRFILE" "$HOMEFILE"
  fi
done

HOMEDOTFILES="$HOME/.dotfiles"
if [ "$DOTFILESDIR" != "$HOMEDOTFILES" ]; then
  ln -sf "$DOTFILESDIR" "$HOMEDOTFILES"
fi

if [ -n "$CODESPACES" ]; then
  # Fix up Codespaces permissions
  chmod 700 /workspaces

  if ! grep -q "script/codespaces-post-start" /workspaces/**/.devcontainer/post-attach-command.sh; then
    # Run the codespaces-post-start script now
    script/codespaces-post-start
  fi
fi
