#!/bin/bash
# Usage: script/setup
# Summary: Install the dotfiles into the home directory

set -e
cd "$(git rev-parse --show-toplevel)"

DOTFILES_ROOT="$(pwd -P)"

# Install dotfiles

echo "==> Installing dotfiles…"
for DOTFILE in ${DOTFILES_ROOT}/*; do
  [[ "$DOTFILE" == **/script ]] && continue
  [[ "$DOTFILE" == **/*.md ]] && continue
  [[ "$DOTFILE" == **/*.txt ]] && continue

  HOMEFILE="${HOME}/.${DOTFILE##*/}"
  if [[ ! -e "$HOMEFILE" ]] || [[ $(ls -l "$HOMEFILE" | awk '{print $11}') != "$DOTFILE" ]]; then
    if [[ -L "$HOMEFILE" ]] && [[ ! -d "$DOTFILE" ]]; then
      ln -sfv "$DOTFILE" "$HOMEFILE"
    else
      rm -rf "$HOMEFILE"
      ln -sv "$DOTFILE" "$HOMEFILE"
    fi
  fi
done

# Install Homebrew dependencies

if [ "$(uname -s)" = "Darwin" ]; then
  echo "==> Installing Homebrew dependencies…"
  if [ -z "$TRAVIS" ]; then
    brew bundle check &>/dev/null || {
      brew bundle --global
    }
  else
    echo "Skipping Homebrew dependencies for CI"
  fi
fi

# Set ZSH as the default shell

if [ "$TRAVIS" != "true" ]; then
  ZSH_PATH=$(command -v zsh)

  if ! grep "$ZSH_PATH" /etc/shells >/dev/null 2>&1; then
    echo "==> Adding $ZSH_PATH to /etc/shells…"
    echo $ZSH_PATH | sudo -n tee -a /etc/shells >/dev/null
  fi

  if [ "$(dscl . -read $HOME UserShell 2>/dev/null | cut -d" " -f2)" != "$ZSH_PATH" ]; then
    echo "==> Setting ZSH as the default shell…"
    sudo -n chsh -s "$ZSH_PATH" "$(whoami)"
  fi
fi

# Install Atom packages

if command -v apm >/dev/null 2>&1; then
  echo "==> Installing Atom packages…"
  while IFS=" " read -r -a line; do
    [ "${#line[@]}" -gt 0 ] || continue
    [ "${line[0]:0:1}" != "#" ] || continue

    pkg_name="${line[0]}"
    if [ ! -d "${HOME}/.atom/packages/${pkg_name}" ]; then
      apm install "$pkg_name"
    fi
  done < "${DOTFILES_ROOT}/atom/default-packages"
fi
