#!/bin/bash
# Usage: script/setup
# Summary: Install all dotfiles into the home directory

set -e
cd "$(git rev-parse --show-toplevel)"

DOTFILES_DIR="$(pwd -P)"

for DOTFILE in * config/**/*; do
  HOMEFILE="$HOME/.$DOTFILE"
  [ -d $DOTFILE ] && DOTFILE="$(echo $DOTFILE/ | sed -e 's://:/:')"
  DIRFILE="$DOTFILES_DIR/$DOTFILE"

  # Don't mess with Codespaces default SSH setup
  if [ -n "$CODESPACES" ]; then
    echo $DOTFILE | egrep -q '^ssh/' && continue
  fi

  # Don't try to install the config folder
  echo $DOTFILE | egrep -q '^config/$' && continue

  # Don't try to install documentation/script files
  echo $DOTFILE | egrep -q '(^script/|\.md$|\.txt$)' && continue

  # Remove .zsh extensions
  echo $DOTFILE | grep -q '\.zsh' && HOMEFILE="$HOME/.$(echo $DOTFILE | sed -e 's/\.zsh//')"

  # Create the parent directory if it doesn't exist
  mkdir -p "$(dirname $HOMEFILE)"

  if [ -L "$HOMEFILE" ] && ! [ -d $DOTFILE ]; then
    ln -sfv "$DIRFILE" "$HOMEFILE"
  else
    rm -rv "$HOMEFILE" 2>/dev/null || true
    ln -sv "$DIRFILE" "$HOMEFILE"
  fi
done

HOME_DOTFILES_DIR="$HOME/.dotfiles"
if [ "$DOTFILES_DIR" != "$HOME_DOTFILES_DIR" ]; then
  ln -sf "$DOTFILES_DIR" "$HOME_DOTFILES_DIR"
fi

if [ -n "$CODESPACES" ]; then
  # Fix up Codespaces permissions
  chmod 700 /workspaces

  if ! grep -q "script/codespaces-post-start" /workspaces/**/.devcontainer/post-attach-command.sh; then
    # Run the codespaces-post-start script now
    script/codespaces-post-start
  fi
fi
