#!/bin/bash
# Usage: script/strap-after-setup
# Summary: Run by Strap after installing Brewfile dependencies

set -e
cd "$(git rev-parse --show-toplevel)"

# script/extract-secrets
# script/set-defaults

# if [ "$SHELL" != "/bin/zsh" ]
# then
  # echo "==> Changing the login shell to zsh…"
  # chsh -s /bin/zsh "$(whoami)"
# fi
