#!/bin/bash
# Usage: script/strap-after-setup
# Summary: Run by Strap after installing Brewfile dependencies

set -e
cd "$(git rev-parse --show-toplevel)"

# script/extract-secrets
# script/set-defaults

if [ "$SHELL" != "/bin/zsh" ]; then
  echo "==> Changing the login shell to zsh…"
  chsh -s /bin/zsh "$(whoami)"
fi

# Ensure auto-update is always enabled
sudo defaults write /Library/Preferences/com.apple.commerce.plist AutoUpdate -bool true
