ZSH_THEME_DIRNAME_PROMPT_PREFIX="in ${PR_BRIGHT_CYAN}"
ZSH_THEME_DIRNAME_PROMPT_SUFFIX="${PR_RESET} "

ZSH_THEME_GIT_REF_PROMPT_CLEAN_PREFIX="${PR_BRIGHT_GREEN}"
ZSH_THEME_GIT_REF_PROMPT_CLEAN_SUFFIX="${PR_RESET}"
ZSH_THEME_GIT_REF_PROMPT_DIRTY_PREFIX="${PR_BRIGHT_RED}"
ZSH_THEME_GIT_REF_PROMPT_DIRTY_SUFFIX="${PR_RESET}"
ZSH_THEME_GIT_REMOTE_STATUS_PROMPT_PREFIX=" ${PR_WHITE}("
ZSH_THEME_GIT_REMOTE_STATUS_PROMPT_SUFFIX=")${PR_RESET}"

ZSH_THEME_HOSTNAME_PROMPT_PREFIX="at ${PR_BRIGHT_MAGENTA}"
ZSH_THEME_HOSTNAME_PROMPT_SUFFIX="${PR_RESET} "

ZSH_THEME_NODE_PROMPT_PREFIX=" node:${PR_BRIGHT_GREY}"
ZSH_THEME_NODE_PROMPT_SUFFIX="${PR_RESET}"

ZSH_THEME_PYTHON_PROMPT_PREFIX=" python:${PR_BRIGHT_GREY}"
ZSH_THEME_PYTHON_PROMPT_SUFFIX="${PR_RESET}"

ZSH_THEME_RUBY_PROMPT_PREFIX=" ruby:${PR_BRIGHT_GREY}"
ZSH_THEME_RUBY_PROMPT_SUFFIX="${PR_RESET}"

ZSH_THEME_SCM_PROMPT_PREFIX="on "
ZSH_THEME_SCM_PROMPT_SUFFIX=" "

ZSH_THEME_USER_PROMPT_PREFIX="${PR_BRIGHT_BLUE}"
ZSH_THEME_USER_PROMPT_SUFFIX="${PR_RESET} "
