export ZSH_THEME_DIRNAME_PROMPT_PREFIX="in ${PR_BRIGHT_CYAN}"
export ZSH_THEME_DIRNAME_PROMPT_SUFFIX="${PR_RESET} "

export ZSH_THEME_GIT_PROMPT_PREFIX="on "
export ZSH_THEME_GIT_PROMPT_SUFFIX=" "
export ZSH_THEME_GIT_REF_PROMPT_CLEAN_PREFIX="${PR_BRIGHT_GREEN}"
export ZSH_THEME_GIT_REF_PROMPT_CLEAN_SUFFIX="${PR_RESET}"
export ZSH_THEME_GIT_REF_PROMPT_DIRTY_PREFIX="${PR_BRIGHT_RED}"
export ZSH_THEME_GIT_REF_PROMPT_DIRTY_SUFFIX="${PR_RESET}"
export ZSH_THEME_GIT_REMOTE_STATUS_PROMPT_PREFIX=" ${PR_WHITE}("
export ZSH_THEME_GIT_REMOTE_STATUS_PROMPT_SUFFIX=")${PR_RESET}"

export ZSH_THEME_HOSTNAME_PROMPT_PREFIX="at ${PR_BRIGHT_MAGENTA}"
export ZSH_THEME_HOSTNAME_PROMPT_SUFFIX="${PR_RESET} "

export ZSH_THEME_NODE_PROMPT_PREFIX=" ${PR_WHITE}node:${PR_RESET}"
export ZSH_THEME_NODE_PROMPT_SUFFIX=""

export ZSH_THEME_PYTHON_PROMPT_PREFIX=" ${PR_WHITE}python:${PR_RESET}"
export ZSH_THEME_PYTHON_PROMPT_SUFFIX=""

export ZSH_THEME_RUBY_PROMPT_PREFIX=" ${PR_WHITE}ruby:${PR_RESET}"
export ZSH_THEME_RUBY_PROMPT_SUFFIX=""

export ZSH_THEME_USER_PROMPT_PREFIX="${PR_BRIGHT_BLUE}"
export ZSH_THEME_USER_PROMPT_SUFFIX="${PR_RESET} "

export ZSH_THEME_VERSION_PROMPT_INVALID_PREFIX="${PR_BRIGHT_RED}"
export ZSH_THEME_VERSION_PROMPT_INVALID_SUFFIX="${PR_RESET}"
export ZSH_THEME_VERSION_PROMPT_VALID_PREFIX="${PR_BRIGHT_WHITE}"
export ZSH_THEME_VERSION_PROMPT_VALID_SUFFIX="${PR_RESET}"
